name: vertiport_surface
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - matplotlib=3.8.4
  - pandas=2.2.3
  - scipy=1.15.2
  - scikit-learn=1.6.1
  - numba=0.61.0
  - cython=3.0.10
  - pip:
    - gurobipy==12.0.1